# Generated by Django 5.0 on 2024-01-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ai_reader', '0004_alter_chat_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='sender',
            new_name='users',
        ),
    ]
