# Generated by Django 4.2.3 on 2024-01-06 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_alter_uploadedfile_file_alter_uploadedfile_vector_db'),
        ('Ai_reader', '0005_rename_sender_chat_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='doc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='pdf.uploadedfile'),
            preserve_default=False,
        ),
    ]
