# Generated by Django 4.2.3 on 2024-01-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_uploadedfile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='vector_db',
            field=models.FileField(default=None, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
