# Generated by Django 5.0.1 on 2024-01-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_uploadedfile_vector_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='vector_db',
            field=models.FileField(upload_to=''),
        ),
    ]
